### ISSUE TITLE
eval time

### ISSUE THREAD

**Issue by chaibosong** [AndyCao1125/SDDPM#5]
we use "CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python main_SDDPM.py  --eval   --pre_trained_path './SDDPM_CIFAR10.pt'   --num_images 500000  --fid_cache './stats/cifar10.train.npz' "  with 7 A100 GPUs, 

and the eval time is 

generating images:   1%|█                                                                | 30/3907 [1:11:32<152:46:18, 141.86s/it]

I think there must be some problem.

**Comment by AndyCao1125** [comment]
Sorry for the confusion. We have corrected the `num_images` parameter in the revised `README.md`; it should be set to 50,000 instead of 500,000. Testing the FID results took us approximately 4-5 hours using 8 A100 40GB GPUs with a total batch size of 2000. It is advisable to utilize as much memory as possible on each GPU. Additionally, the number of images used for evaluating the FID results is configurable; you can set this number according to your needs, e.g., 10,000 images. However, please note that using too few images may affect the accuracy of the FID scores.

**Comment by chaibosong** [comment]
Thank you very much for your prompt reply！

**Comment by AndyCao1125** [comment]
Please see issue #6.
